

export const constVar = {

    hereEmail: "εδώ, δίνεις το email σου*",
    herePass: "εδώ, τον κωδικό σου*",
    forgotPass: "Ξέχασες τον κωδικό σου;",
    login: "Είσοδος",
    askForPostsFavorites: 'Η δημιουργία του post πραγματοποιήθηκε επιτυχώς. Μπορείς να το αποθηκεύσεις στα αγαπημένα έτσι ώστε να μην συμπληρώσεις ξανά τις πληροφορίες.',
    go: "Πάμε",
    changePassDescription: "Δώσε μας το email που χρησιμοποίησες για την εγγραφή σου και θα σου στείλουμε έναν νέο κωδικό τον οποίον μπορείς να τον αλλάξεις.",
    fillFirst: "Συμπληρώστε τα πεδία πρώτα.",
    passLength: "Ο κωδικός αποτελείται απο τουλάχιστον 5 χαρακτήρες.",
    register: "Εγγραφή",
    emailApproved: "Η εξακρίβωση του email ολοκληρώθηκε επιτυχώς!",
    goConfirm: "Πάμε για επιβεβαίωση",
    expiredPass: "ο κωδικός είναι λάθος ή έχει λήξει",
    checkEmail: "δεν έλαβες κάποιο email; Τσέκαρε μήπως πήγε στα σπαμ σου ✉",
    retry: "retry",
    sthWentWrong: "Ουπς, κάτι πήγε λάθος",
    passLengthNote: "*Ο κωδικός αποτελείται απο 5 χαρακτήρες και άνω",
    carTitle: "Όχημα",
    carBrandTitle: "Μάρκα",
    carAgeTitle: "Χρονολογία",
    carAgeLabel: "Χρονολογία οχήματος",
    confirmPass: "επιβεβαίωση κωδικού*",
    man: "Άντρας",
    woman: "Γυναίκα",
    age: "ηλικία",
    phone: "αριθμός τηλεφώνου*",
    fullName: "ονοματεπώνυμο*",
    passwordDifferent: "Ο κωδικός με τον κωδικο επιβεβαίωσης είναι διαφορετικοί.",
    givePass: "δώσε έναν νέο κωδικό",
    giveCurrentPass: "δώσε τον τωρινό κωδικό",
    newPass: "Νέο password",
    contactForm: "Φόρμα επικοινωνίας",
    termsTitle: "Όροι && προϋποθέσεις",
    personalInfo: "Προσωπικά στοιχεία",

    email: "Email",
    mobile: "Αριθμός τηλεφώνου",
    age: "Ηλικία*",
    socialTitle: "Κοινωνικά δίκτυα",
    carBrand: "Μάρκα αυτοκινήτου",
    facebook: "Facebook",
    instagram: "Instagram",
    car: "Όχημα",
    rateNow: "Αξιολόγησε τώρα",

    submit: "Υποβολή",
    initialDate: 'Αρχική',
    endDate: 'Τελική',
    returnStartDate: 'Από',
    returnEndDate: 'μέχρι',

    startDestination: 'Αφετηρία προορισμού',
    endDestination: 'Τελικός προορισμός',
    phoneIncorrect: 'Ο αριθμός δεν αντιστοιχεί σε κάποιο νούμερο',
    instagramIncorrect: 'Ο λογαριασμός δεν είναι έγκυρος',
    selectAge: 'Επιλογή ηλικίας',
    selectCar: 'Επιλογή μάρκας',
    selectCarAge: 'Επιλογή χρονολογίας',
    favoritesTab: "αγαπημένες αναζητήσεις",
    searchTab: "αναζήτηση",
    searchBottomTab: "Αναζήτηση",
    createPostBottomTab: "Δημιουργία post",
    selectCarAge: 'Επιλογή χρονολογίας',
    contactInputPLaceholder: 'Οποιαδήποτε απορία,ερώτηση,πρόβλημα η πρόταση έχεις μπορείς να επικοινωνήσεις μαζί μας..',
    previewProfile: 'Προβολή προφίλ',
    changePass: 'Αλλαγή κωδικού',
    filters: 'Φίλτρα'
}