

export const constVar = {

    hereEmail: "εδώ, δίνεις το email σου",
    herePass: "εδώ, τον κωδικό σου",
    forgotPass: "Ξέχασες τον κωδικό σου;",
    login: "Είσοδος",

    go: "Πάμε",
    changePassDescription: "Δώσε μας το email που χρησιμοποίησες για την εγγραφή σου και θα σου στείλουμε έναν νέο κωδικό τον οποίον μπορείς να τον αλλάξεις.",
    fillFirst: "Συμπληρώστε τα πεδία πρώτα.",
    passLength: "Ο κωδικός αποτελείται απο τουλάχιστον 5 χαρακτήρες.",
    register: "Εγγραφή",
    emailApproved: "Η εξακρίβωση του email ολοκληρώθηκε επιτυχώς!",
    goConfirm: "Πάμε για επιβεβαίωση",
    expiredPass: "ο κωδικός είναι λάθος ή έχει λήξει",
    checkEmail: "δεν έλαβες κάποιο email; Τσέκαρε μήπως πήγε στα σπαμ σου ✉",
    retry: "retry",
    sthWentWrong: "Ουπς, κάτι πήγε λάθος",
    passLengthNote: "*Ο κωδικός αποτελείται απο 5 χαρακτήρες και άνω",
    carTitle: "Όχημα",
    carBrandTitle: "Μάρκα",
    carAgeTitle: "Χρονολογία",
    carAgeLabel: "Χρονολογία οχήματος",
    confirmPass: "επιβεβαίωση κωδικού",
    man: "Άντρας",
    woman: "Γυναίκα",
    age: "ηλικία",
    phone: "αριθμός τηλεφώνου",
    fullName: "ονοματεπώνυμο",
    passwordDifferent: "Οι κωδικοί είναι διαφορετικοί.",
    givePass: "δώσε έναν νέο κωδικό",
    newPass: "Νέο password",
    personalInfo: "Προσωπικά στοιχεία",

    email: "Email",
    mobile: "Αριθμός τηλεφώνου",
    age: "Ηλικία",
    socialTitle: "Κοινωνικά δίκτυα",
    carBrand: "Μάρκα αυτοκινήτου",
    facebook: "Facebook",
    instagram: "Instagram",
    car: "Όχημα",
    rateNow: "Αξιολόγησε τώρα",

    submit: "Υποβολή",
    initialDate: 'Αρχική',
    endDate: 'Τελική'
}